### ISSUE TITLE
Newtonsoft.json warning still exists in 4.4.10

### ISSUE THREAD

**Issue by tiritas** [plivo/plivo-dotnet#130]
This was supposed to be fixed in this version, but it's still there:

Warning	NU1603	Plivo 4.4.10 depends on Newtonsoft.Json (>= 10.0.0) but Newtonsoft.Json 10.0.0 was not found. An approximate best match of Newtonsoft.Json 10.0.1 was resolved.

**Comment by huzaif-plivo** [comment]
@tiritas We request you to test our latest version of SDK [V4.15.0](https://github.com/plivo/plivo-dotnet/releases/tag/v4.15.0) which doesn’t contain any such warnings.
