### ISSUE TITLE
RestSharp version too old

### ISSUE THREAD

**Issue by colinangusmackay** [plivo/plivo-dotnet#18]
The version of RestSharp used by Plivo is from September 2012, the superseded version has a breaking change which means that in solutions that need the newer version of RestSharp for other code cannot use the Plivo NuGet package.

Either 
* Update the Plivo code to the newer RestSharp package and resolve the breaking change (RestClient.BaseUrl is now a Uri rather than a string), or;
* To keep compatibility with both RestSharp 104.x and 105.x change the code to set the baseUrl in the constructor of RestClient rather than setting a property once the RestClient is instantiated.

**Comment by EIrwin** [comment]
@colinangusmackay I updated the nuget package to 105.0.1 and changed the client initialization to the following:
  
    client = new RestClient(string.Format("{0}/{1}/Account/{2}", PLIVO_URL, version, AuthID));
    client.Authenticator = new HttpBasicAuthenticator(AuthID, AuthToken);
    client.UserAgent = "PlivoCsharp";

**Comment by EIrwin** [comment]
@colinangusmackay any update on this issue?

**Comment by sdebnath** [comment]
@tsudot this can be closed now since #22 went in
