### ISSUE TITLE
SDK PhoneNumber List does not support "city" param like documentation claims

### ISSUE THREAD

**Issue by lilmidnit** [plivo/plivo-dotnet#187]
According to Plivo API documentation there should be a "city" option in the PhoneNumber List method.

https://www.plivo.com/docs/numbers/api/phone-number#search-phone-numbers

Please address this issue asap.

**Comment by huzaif-plivo** [comment]
@lilmidnit Thank you for the feedback! We have fixed this issue in our [recent release](https://github.com/plivo/plivo-dotnet/releases/tag/v5.7.3); please update your dotnet SDK version to take advantage of the fix.
