### ISSUE TITLE
A2P 10DLC - Campaign status parameter getting from campaign API is missing

### ISSUE THREAD

**Issue by walter-234** [plivo/plivo-dotnet#253]
I am getting an issue I encountered while integrating Plivo in my .NET application. I have been working on registering an a2p campaign, referring to the official documentation provided by Plivo at https://www.plivo.com/docs/sms/api/10dlc/campaign/.

- Campaign Status Retrieval:
As part of my integration, it is crucial for me to retrieve the campaign status of a profile. However, upon exploring the Plivo .NET package, it appears that there is no direct support for this functionality. I kindly request your assistance in checking and updating the .NET package to include support for obtaining the campaign status of a profile. This enhancement would greatly benefit developers like myself who are leveraging the Plivo API within their .NET applications.
![image](https://github.com/plivo/plivo-dotnet/assets/52630282/2e86a91a-da16-4df6-81b8-ee4fe755a39f)

- Error Details for Failed Campaigns:
Is there a mechanism in place to push error details when a campaign fails? It would be immensely helpful if we could receive detailed information about why a campaign failed, enabling us to diagnose and address any underlying issues promptly. If such functionality doesn't exist yet, I would appreciate it if you could consider incorporating this feature into the Plivo .NET package.

I genuinely appreciate the effort and dedication you put into maintaining this public GitHub repo. Your prompt attention to these matters would significantly contribute to the overall usability and developer experience associated with Plivo's .NET integration. As an active user of Plivo, I believe that these enhancements will benefit the community as a whole.

My Plivo package integrated version: 5.31.0

**Comment by narayana-plivo** [comment]
@walter-234 we have already added support campaign registration status filter( >= v5.40.0 versions)

**Comment by narayana-plivo** [comment]
@walter-234 Closing the issue. Its fix already deployed on latest version
