### ISSUE TITLE
Beep not supported in Wait

### ISSUE THREAD

**Issue by kobyl** [plivo/plivo-dotnet#27]
Hello,

  It looks like Wait now has beep detection. (https://www.plivo.com/docs/xml/wait/).
However, PlivoXml.cs still doesn't support the key.

	    public class Wait : PlivoElement
    {
        public Wait(dict attributes)
            : base(attributes)
        {
            Nestables = new list() { "" };
            ValidAttributes = new list()
            {   "length", "silence","minSilence"
            };
            addAttributes();
        }
    }

Can someone add this? Otherwise the API just throws. :(

Thanks!

Koby

**Comment by Ramya-Raghu** [comment]
Beep attribute has been added in the latest release - Plivo 3.0.1 .
