### ISSUE TITLE
Sms Message Api not updated

### ISSUE THREAD

**Issue by nirpet** [plivo/plivo-dotnet#40]
Hi,

I'm using RestApi to send messages and get status of messages.
The get_message method returns an object of type IRestResponse<Message>

The Message object contains the following properties:

public string cloud_rate { get; set; }
public string carrier_rate { get; set; }
public string message_direction { get; set; }
public string to_number { get; set; }
public string message_state { get; set; }
public string total_amount { get; set; }
public string from_number { get; set; }
public string message_uuid { get; set; }
public string message_time { get; set; }
public string resource_uri { get; set; }
public string message_type { get; set; }
public string total_rate { get; set; }
public int units { get; set; }

While the response from the message api contains the following fields:

"api_id":
"error_code"
"from_number"
"message_direction"
"message_state"
"message_time"
"message_type"
"message_uuid"
"resource_uri"
"to_number"
"total_amount"
"total_rate"
"units"

I want to get the error code from the response.  
is there a way to do it using this library?

Thanks

**Comment by Athl33t** [comment]
Is there still no way to get message_state on message create via this library?
