### ISSUE TITLE
Functions to compute and verify signature missing in 4.0

### ISSUE THREAD

**Issue by BioChristou** [plivo/plivo-dotnet#42]
In the 4.0 branch, the Plivo project currently targets .Net Standard 1.1.  Please consider targeting .Net Standard 1.3 or newer. It appears there are packages that are not available to 1.1, for example `HMACSHA1` ( https://www.nuget.org/packages/System.Security.Cryptography.Algorithms ), required to generate/verify an `X Plivo Signature`.

**Comment by plivo-sdks** [comment]
@BioChristou Thanks for pointing that out. I see that we have a dummy placeholder for the signature validation and are in the process of adding functions to compute and verify the V2 signature.

One way is to write a custom version of `HMACSHA256`. The other way (and a much cleaner way) is to drop support for .NET Framework 4.5.x. Let me try out both the ways and see what can be done here.

**Comment by BioChristou** [comment]
@plivo-sdks thank you! I was initially hoping to PR in a signature generation method when I encountered what I mentioned in my first post. Looking forward to hearing about your findings.

**Comment by plivo-sdks** [comment]
Fixed in 94f83852701369eeaac938184ede856bb7cc9252
