### ISSUE TITLE
Using Plivo  with .netframework4 and WebAPI 1

### ISSUE THREAD

**Issue by samih-dev** [plivo/plivo-dotnet#46]
Hi

I'm new to Pilvo 

I see from docs that Plivo should be supported with .netframework version 4 and up

I have a project with MS web API (version 1), with main page served as ASP MVC Page , 
I installed Pilvo using Nuget and build pass, but got exception when trying to lunch the main page

I installed the latest stable version  - 3.0.8

screenshot:
![capture](https://user-images.githubusercontent.com/3106856/34070521-8d2908be-e270-11e7-81fa-0819afa4fc4e.PNG)

After some investigations, it seems related to Assembly Strong Name  -  I didn't face such issue before, it could be related to the project?  or it is a general Pilvo Assemblies issue?

can you please help?
Thanks

**Comment by plivo-sdks** [comment]
@samih-dev We don't have strong named assemblies yet. AFAIK we didn't sign 3.0.8 either. Can you check if you are able to use other unsigned assemblies fine? If all of them are signed, you might want to sign Plivo package yourself for now. Let me know if that doesn't solve the issue.

**Comment by samih-dev** [comment]
@plivo-sdks I was able to use unsigned assemblies, yes, like Elmah package for logging for example.

**Comment by samih-dev** [comment]
Attaching screenshot from my env, Plivo assembly Strong Name property is set to true
![Uploading Capture.PNG…]()

**Comment by samih-dev** [comment]
@plivo-sdks  3.0.7 version seems fine, it has the Strong Name flag set to false - I was able to send SMS mesages successfully with this build, 
Please verify the issue with the newest version/same env and frameworks, 
Thanks!

**Comment by plivo-sdks** [comment]
@samih-dev I see. I've rebuilt 3.0.8 and uploaded the package on Nuget as 3.0.9. Please try that and let us know if you keep facing this issue.
