### ISSUE TITLE
No support for ASP.NET core

### ISSUE THREAD

**Issue by huzaynbolt** [plivo/plivo-dotnet#47]
Any time I tried using this package on an .NET Core framework APP, I keep getting an error message that says, "Not Supported on this framework"

**Comment by plivo-sdks** [comment]
@huzaynbolt Which version of the SDK are you trying to use? 3.0.x doesn't support .NET core. Check out the pre-release versions that support .NET core: https://github.com/plivo/plivo-dotnet/releases/tag/v4.0.0-beta2
