### ISSUE TITLE
Cannot install on project targeting .net 4.5.2

### ISSUE THREAD

**Issue by claudiagoga** [plivo/plivo-dotnet#48]
Hi, I am trying to install Plivo SDK to a asp.net MVC project (.net 4,5,2) using nuget packages but it show the below error. Any ideas on how to install the sdk?

`Could not install package 'Plivo 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. `

**Comment by vinsaTimeparity** [comment]
I think Plivo has officially nuked its support for .Net 4.5 (which is pretty strange and honestly leaves us Flabbergasted !)

https://www.plivo.com/blog/introducing-plivo-server-side-sdks-v4/

> .NET SDK: The SDK has been modified to target .NET Standard 1.3 to use Cryptography package for signature validation. Since .NET Standard targets .NET Framework 4.6+ and .NET Core 1.0+, we had to drop support for .NET Framework 4.5

**Comment by plivo-sdks** [comment]
@claudiagoga & @vinsaTimeparity You can still use the 4.x beta versions if you don't need to use the signature validation methods.

New features and APIs will be added only to the latest version though, so you might want to consider remodeling or upgrading to 4.6.
