### ISSUE TITLE
Could not load file or assembly 'System.IO.FileSystem'

### ISSUE THREAD

**Issue by developer-argus** [plivo/plivo-dotnet#57]
Hello,
I got this exception on calling 
**PlivoApi.Message.Create Method.**

Exception:

> Could not load file or assembly 'System.IO.FileSystem, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies

Plivo version: 4.1.0

Regards.

**Comment by ultravelocity** [comment]
Experiencing the same issue on a .NET 4.6.2 project. Had to add a the System.IO.FileSystem nuget package. Any plans to fix this?

**Comment by nixonsam** [comment]
@developer-argus This was release 6months ago. You can find it in the latest [version](https://github.com/plivo/plivo-dotnet/releases/tag/v4.4.1)
