### ISSUE TITLE
Library breaks with latest version of RestSharp

### ISSUE THREAD

**Issue by scushen** [plivo/plivo-dotnet#63]
Resharp updated to v106.3.1 

and you get the error:
Could not load type 'RestSharp.HttpBasicAuthenticator' from assembly 'RestSharp,API' looks like RestSharp was updated and they moved some stuff around in 105.0.2+

Rollback back to < 105.0.1

**Comment by nixonsam** [comment]
@scushen Let us know if you are still facing any issues.
