### ISSUE TITLE
Version 4.0 and up breaks will not install

### ISSUE THREAD

**Issue by scushen** [plivo/plivo-dotnet#71]
Could not install package 'Plivo 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by nixonsam** [comment]
@scushen Plivo Dotnet SDK Supported .NET versions are as below.

.NET Framework 4.6+ and .NET Core 1.0+.
