### ISSUE TITLE
No WebProxy created on SystemHttpClient when there are any proxySettings.

### ISSUE THREAD

**Issue by barozi** [plivo/plivo-dotnet#84]
Hello,

Why on the SystemHttpClient there is not created WebProxy? Is it because the library is targetting NETStandard 1.3? 

If so, when it will support the 2.0 where the WebProxy class is added to System.Net namespace?

Best regards,
Bartosz

**Comment by nixonsam** [comment]
@barozi Please check https://github.com/plivo/plivo-dotnet/releases/tag/v4.4.0 which supports netcore 2.0.

Let us know in case of any further concerns.
