### ISSUE TITLE
Message.Create Does not work in Windows Forms Application

### ISSUE THREAD

**Issue by rajhalli** [plivo/plivo-dotnet#97]
Tried out current package (v4.2.3), the sample code works well in Windows Console Application, try to run the same code in Windows Forms Application Message.Create never returns the control back to the application. SMS gets delivered to the phone though. Simple Forms Application, and sample code with valid auth_id and auth_token

**Comment by rajhalli** [comment]
Here is the code, removed actual auth id, token, source no and dest no.
        private void button1_Click(object sender, EventArgs e)
        {
            var api = new PlivoApi("aith_id", "auth_token");
            try
            {
                var response = api.Message.Create(
                    src: "hidden_src",
                    dst: new List<String> { "hidden_dest" },
                    text: "Test Message"
                );

                string SomeString = response.Message;
            }
            catch (PlivoRestException ex)
            {
                string AnotherString = ex.Message;
            }
        }

**Comment by rajhalli** [comment]
Visual Studio 2015
.NET 4.6.1
Plivo 4.2.3

**Comment by obkdev** [comment]
We have the same issue calling from a web api.  Just hangs. 

VS 2015
.Net 4.7.2
Plivo 4.4.0

Might be related to calling a async http call in an sync method - could we have a CreateAsync?

**Comment by obkdev** [comment]
So I think it is an async context issue, as I can resolve the issue by wrapping it in a Task and awaiting it and manually setting ConfigureAwait.

Like so:

```
var plivo = new PlivoApi(_key, _password);
MessageCreateResponse response = await Task.Run(() => plivo.Message.Create(destinations, content, sourceNumber)).ConfigureAwait(false);
```

Hopefully this can help someone.

**Comment by nixonsam** [comment]
@obkdev Thank you for sharing your suggestion!

@rajhalli Feel free to contact our [support team](https://support.plivo.com/support/home) any time in case of any concerns or queries.
