### ISSUE TITLE
Library not strong named

### ISSUE THREAD

**Issue by dberroa** [plivo/plivo-dotnet#98]
We have to strong name our project DLLs which means that every reference also needs to be strong named. I get an error that this library requires a strong name assembly when building with it. For our projects to fix, we right click the project file and then go to signing and make a key. Is it possible for you to add this to the nuget version?

**Comment by huzaif-plivo** [comment]
@dberroa Unfortunately, we will not be able to support this at the moment and currently not in our roadmap too, In case if you are facing any challenges while performing strong name, you can refer to our docs [here](https://github.com/plivo/plivo-dotnet/blob/v4.2.0/STRONGNAMING.md). The reason for the same is also mentioned here.
